id: P000545
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4265
  title: སངས་རྒྱས་བཀྲ་ཤིས་སམ་སྲོག་བདག་རྡོ་རྗེ་དཔའ་བོ་རྩལ་གྱི་བྱུང་བ་བརྗོད་པའི་ས་བོན་ཉེར་མཁོ
  author: ''
  volumes:
    fe66df011e294304bc9acb3ba8023427:
      image_group_id: I1KG4991
      title: Volume 1 of sangs rgyas bkra shis sam srog bdag rdo rje dpa' bo rtsal
        gyi byung ba brjod pa'i sa bon nyer mkho
      volume_number: 1
      total_pages: 50
      base_file: v001.txt
