id: opecha:P000545
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4265
  title: སངས་རྒྱས་བཀྲ་ཤིས་སམ་སྲོག་བདག་རྡོ་རྗེ་དཔའ་བོ་རྩལ་གྱི་བྱུང་བ་བརྗོད་པའི་ས་བོན་ཉེར་མཁོ
  volume: ''
  author: ''
